"""Initial migration.

Revision ID: 901824814397
Revises: 52a401750a76
Create Date: 2025-01-28 19:46:50.726934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901824814397'
down_revision = '52a401750a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.add_column('teachers', sa.Column('principal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'principals', ['principal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'principal_id')
    op.alter_column('assignments', 'state',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###
